/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 06.04.2026 11:56:52

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1440;
#else
constexpr int kTensorArenaSize = 416;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,39 } };
const TfArray<1, float> quant0_scale = { 1, { 0.043835628777742386, } };
const TfArray<1, int> quant0_zero = { 1, { 43 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 281, -327, 20, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00027929371572099626, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*20] = { 
  50, 0, 86, -65, -10, 48, 82, -76, -96, 87, 46, -10, 50, -81, 50, 12, -35, -87, 13, 28, 
  56, 55, -44, -59, -127, 14, 1, -67, 12, -51, -25, 31, 5, 40, -38, 46, 50, 74, -53, 30, 
  -77, -14, 98, -3, -83, -81, -76, -37, 84, 23, 87, -95, -66, 64, -7, 30, 6, -10, 8, 75, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,20 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0057163494639098644, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[20] = { -116, -466, 631, -101, 764, 136, 378, -6, -274, 765, 0, 269, 313, -177, 577, -541, -141, -168, 532, 38, };
const TfArray<1, int> tensor_dimension3 = { 1, { 20 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00017466260760556906, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[20*50] = { 
  27, -60, 63, 77, -9, 19, 40, 30, 22, -56, 66, 56, -81, 37, -34, 70, -60, 72, -27, 36, 52, -42, 6, 21, 13, -35, -21, -18, 2, -75, 50, -12, -3, -33, -41, 4, 84, 55, 31, -11, -72, 42, 55, -9, 21, -8, -48, 11, -72, -35, 
  -38, 41, -21, -32, -66, -34, 46, 43, -56, -40, 9, -73, 71, -47, -45, 60, -44, 17, -28, 47, 20, -42, -61, 58, 79, -90, -51, -17, 34, 44, 5, 24, 59, 48, 48, -66, 59, 18, -95, -23, 62, 11, 7, 9, -48, 12, -19, 30, 13, -73, 
  -15, 5, 29, -24, -18, 26, -14, 1, 92, -50, -37, 9, 83, -28, 3, 28, -8, 12, -21, -61, 93, 116, 69, -73, 78, -1, 100, 91, -43, 48, -67, 102, -1, 94, -60, -43, 24, 67, 26, -6, -17, -17, 55, 78, -32, 89, 42, -19, 90, 41, 
  40, 56, -50, -40, -22, 63, -53, -7, -24, 67, 72, -52, 18, 6, -9, 43, 31, 21, -61, 28, -55, -14, -65, 7, -58, 37, -40, -63, -40, -40, -46, 5, -67, -22, -30, -58, -35, -55, -88, -33, 61, 11, 51, -84, -37, -45, -3, 59, -52, 7, 
  -31, -65, -11, -20, -36, 81, -12, 35, 26, 66, -64, 72, 1, -3, 46, 69, -46, 49, -58, 19, 2, 102, -19, -11, 86, 17, 75, 44, -1, 33, -39, -40, 8, -28, 56, 88, 45, 92, 106, 63, -34, -7, 25, 70, -61, 86, -41, -15, -26, -37, 
  -59, -53, -22, 1, -76, 59, -33, -16, 4, -49, -69, 57, -24, -5, 18, -32, 12, 39, -58, 12, 91, -70, -63, -65, -23, 72, -29, 55, 41, 27, 82, -67, 55, 33, 50, -5, 56, 34, 46, -31, -63, 14, -33, 3, -2, 31, 21, -7, 13, 10, 
  62, -46, 75, 27, -8, 52, -45, 14, 70, -12, 0, 33, 49, -40, -72, -8, -5, 39, 2, 72, 27, -5, -21, 26, -34, 74, 78, -3, -67, -9, 7, -46, 49, 81, -28, 69, 32, -45, 42, 57, 44, 67, 2, -70, -42, -53, -48, 86, 54, 71, 
  -10, 46, -14, 58, 79, -44, 48, -62, 31, 15, 4, -57, 50, -18, -65, -50, 60, -69, 22, 64, 52, 50, -53, -53, 29, -87, -10, -57, 59, -42, 70, 78, -80, -44, 58, -47, -74, 31, -35, 7, 11, 33, -67, 37, 56, -1, 7, -26, 68, 4, 
  42, 56, 40, -71, -19, 58, 5, -17, -88, -31, 16, 10, 80, 49, 15, -58, 5, -66, 24, -53, -97, -21, 42, 54, 43, 3, -13, 0, 5, 22, 75, 24, -85, 12, 30, 70, 24, 13, -85, -46, 62, -104, 35, 25, -27, -40, 7, 25, 45, 2, 
  30, -21, 114, -13, 66, -28, -53, 46, 23, 30, 75, -35, 36, -36, 26, 66, -8, -70, -2, -22, 115, 42, -69, -14, 6, 34, 99, 38, -68, -54, 26, 85, -16, -53, -50, -62, 68, 32, -9, 54, -32, 99, 77, -27, 21, 31, -3, 40, -39, -7, 
  -52, 9, 11, -71, -34, 13, 77, -56, -18, 17, -65, 17, 22, 63, 37, 54, -53, -67, -1, -47, 21, -17, -64, 28, 54, -53, 74, -68, -30, 46, -50, 17, 25, 52, 13, 8, 18, -65, 29, -35, -28, -46, 47, -43, 5, -41, 76, -58, 23, -60, 
  -77, 34, -14, -63, 15, -28, 14, 65, 73, -3, -60, 49, 27, -44, -32, -5, -63, -30, 34, 2, 63, 47, 0, -42, 36, 56, 6, 27, 7, -58, -7, 43, 28, 13, 42, 12, -23, -40, 32, -51, 42, -31, -10, -32, -29, 40, -32, 43, -13, -49, 
  -65, 69, -5, 2, 4, 47, -58, -39, -44, -34, 44, -65, -17, 47, 53, 67, 40, 51, 8, 29, -70, 44, 41, -77, 28, -10, 89, -4, -22, 8, -71, 35, 27, 93, 36, 30, -24, -50, -12, -64, -40, 4, -41, 39, -2, 47, -49, -25, 17, -28, 
  9, -8, 39, -35, 44, 26, -71, -37, -49, 51, 52, -33, -65, 7, 36, 57, 51, -9, 41, -20, -3, -35, 35, 58, 8, -4, 7, 55, -76, 26, 49, -53, -50, -34, 62, -24, -16, -14, 4, 68, -78, 62, 59, -50, -55, -45, -59, -8, 48, 13, 
  40, -45, 86, 17, 47, 46, 26, -59, 104, 53, -15, -37, -50, 38, -46, 70, 21, 51, -68, 0, 0, 33, -61, 37, 22, 20, 10, 68, 23, -4, 15, 87, -28, 97, -40, 39, 45, -32, 95, 14, 16, -28, 50, 45, -59, 86, -50, -14, 77, 55, 
  47, 46, -127, 59, -36, 36, 53, -45, 9, -8, 66, -17, 29, 10, -50, 24, -81, 60, 32, 78, -66, -37, 53, -47, -17, -37, 20, -94, 1, 23, 56, -86, 38, 52, -2, -77, 21, 68, -84, -70, -37, 17, -51, -39, 76, -39, 24, 23, 2, -22, 
  32, -58, 48, -25, -4, 22, -36, -20, -17, -28, -27, -69, 16, 45, 51, 12, -39, -31, -19, -80, 72, 21, -9, 36, -76, -22, 38, -29, -70, 71, -45, -31, 51, 3, 4, 12, 15, 1, -6, -78, -10, -18, 45, -41, 52, -2, 63, 26, 10, -42, 
  61, 40, 41, -74, -23, 72, -19, 31, -2, 55, 38, -48, 63, 75, -34, -12, -56, -52, 66, -15, 28, -22, -56, -46, -31, -74, -62, -79, -21, 38, -41, 49, 10, -20, 3, 36, -77, 0, -49, 27, -67, -80, 2, -78, -40, 11, 15, -9, 34, 14, 
  27, 26, 78, -23, 12, 14, -77, 67, 78, -11, -74, 56, -57, -77, -31, 103, 14, -68, 68, 67, -5, 17, 23, 65, 67, 106, -36, 62, 48, 58, 59, 41, -64, 76, 5, 9, -8, 73, 101, 61, 22, -26, -48, -36, -56, 3, 60, -44, 40, -24, 
  -48, 11, 74, 10, -63, 29, -35, -8, 39, 62, -82, -3, -47, 6, -60, -70, -24, 72, -16, 38, 20, -56, 46, 70, -25, -42, 17, 66, -50, 65, -36, 66, 8, -4, -15, 35, 34, 72, -49, -9, -59, -9, -27, 68, -78, -49, 29, 67, -38, -52, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 20,50 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0037153435405343771, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[50] = { 0, -46, 402, -1, 544, 32, -918, 378, 944, 37, -448, 481, -24, -596, -151, 544, -171, 82, -242, 38, 658, 1019, -127, -617, 138, 654, 1181, 804, -562, -62, -526, 446, -168, 463, -237, 28, 334, 729, 833, 210, 0, 356, 122, 360, -813, 330, 219, -17, -4, 781, };
const TfArray<1, int> tensor_dimension5 = { 1, { 50 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00013832171680405736, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[50*39] = { 
  0, 37, 39, 13, -3, 22, 71, -1, 70, -75, 51, -26, 19, -64, 35, -64, 36, 4, 67, -77, -14, -16, 52, -35, 31, 52, -57, 36, 19, -18, -44, -51, 22, 24, 10, 21, 28, 38, -77, 
  -118, 94, 3, -32, -45, 50, -44, -30, -16, 73, 30, 33, -23, -37, -40, 12, -23, 87, -33, 30, -84, 16, -94, -24, -28, -20, -43, -1, 59, -40, 75, 60, -16, -75, 0, 27, 9, -93, 30, 
  74, -12, -49, -72, -71, 9, 47, -35, 74, -56, -24, -42, -42, -55, -2, -64, 53, -87, -12, 44, 38, -91, -71, 22, 75, -60, 75, 55, 0, 44, -71, 57, 32, 63, 9, -48, -58, 17, 59, 
  -48, -63, 57, 75, 69, 66, -23, -20, -58, -7, 44, 70, -33, -36, 26, -1, -79, 56, -62, 45, -51, -59, -58, 59, 78, -5, -50, 59, 57, 45, 20, -42, 11, -24, -65, 73, 41, -48, -24, 
  91, -41, -64, 34, -59, -56, 56, 22, 1, -32, 11, -59, 41, -13, -51, 8, 30, -85, -39, -42, 61, 31, 83, -15, -67, -49, 67, 70, -71, 83, 20, 34, 70, -49, -41, 11, -28, -13, 1, 
  -20, -57, -65, 21, -62, -49, -5, 32, -66, -70, -22, -34, -18, -26, -72, -75, 55, 27, -81, -23, 68, 56, 47, 32, 19, 19, 2, -61, 63, 77, -39, 11, -70, 4, -69, 37, 7, 13, -9, 
  -2, -38, -73, -84, 24, 8, -21, -46, -42, 27, -12, 60, 55, 23, 48, -56, -38, 23, -82, -82, -59, -14, -9, -14, -50, -46, -19, -40, 9, -69, 53, 16, 59, -79, -18, -48, -55, 82, -73, 
  99, 52, 30, 78, -29, -28, -78, 21, 66, -59, 84, 30, 22, 41, -63, -38, -17, 64, -1, 81, -50, 79, -44, -66, -47, 49, 61, -5, -37, 54, 1, -59, 82, -69, -76, 25, -10, -67, -27, 
  90, 29, 73, 35, -3, -72, -36, -49, 76, -47, 55, -17, 47, -13, 0, -88, -2, -72, 28, 22, -81, 30, 32, -58, 49, -56, -33, -80, -28, 94, -95, 19, -36, 63, 14, 5, 4, 57, 0, 
  -74, 3, 57, -14, -82, 63, 68, -64, -15, 67, 54, -33, -37, 63, 9, 13, 23, 19, -80, 26, 46, -69, 15, -66, -73, -61, -27, -46, -48, -28, -69, -74, 44, 2, 66, -9, 63, -59, 69, 
  56, 51, -33, 8, -49, -58, -50, -41, -71, 13, -15, -56, -77, -84, 77, -2, 12, -26, 51, -57, -27, -16, 74, 83, 24, -53, -98, 71, 55, -36, 74, -14, -35, 27, 58, -58, 2, 73, 10, 
  13, -2, -86, 49, 61, 11, 35, 78, -23, -18, 31, -22, -14, 108, -4, 20, 40, 41, -28, 6, -63, -34, 43, 68, 60, -22, 79, 32, -80, 15, 20, -4, 40, 1, -70, 18, 47, 23, 29, 
  -56, -36, -80, 77, -17, 39, 59, 1, 38, -66, -31, -46, -41, -79, 39, 44, 0, -2, -38, 24, 48, -8, -89, 2, -37, 0, 0, -15, -6, 78, -65, -43, 9, -9, 55, -73, -71, -41, -88, 
  -12, 53, 77, 17, 36, 44, -62, 25, -63, -32, -85, 67, 25, -63, 18, 22, 56, 75, -51, 42, 21, -83, -34, -31, 0, 59, 36, -42, -72, -83, -54, 23, -35, -23, 17, 50, 5, 12, -57, 
  62, -44, -42, -45, 81, -31, -27, -3, 72, -9, -44, -70, 86, -69, -52, 14, -84, -24, 53, -12, -12, -17, -48, 75, 8, 81, 62, -77, 2, 22, 42, -35, 48, -55, -62, 58, -33, 56, 0, 
  37, -11, 12, -15, -7, 30, 58, -29, -81, -50, -6, -41, 13, -11, 40, 14, 69, -28, -48, -3, 34, -37, -53, 43, -3, -67, 70, 87, -79, -48, 54, 53, -52, 59, 59, 81, 1, 65, 58, 
  -6, -34, -26, -34, -70, 55, 36, 85, -62, 60, -22, 71, 36, -17, -41, -68, -9, 1, -59, 0, 13, 57, -71, 50, -46, -43, 29, -68, -66, 31, 38, 40, 24, 30, 61, -31, 17, 81, -33, 
  11, 48, -19, -20, -24, 24, -34, -61, 38, -6, -63, -79, -9, -45, 91, 62, -86, 69, -54, -50, -37, 14, -58, 56, 29, -51, 71, -55, 66, 31, 14, -47, -68, -3, 77, 58, 7, -38, 52, 
  -98, 4, -3, -17, -74, -20, -34, 89, -33, 39, -70, 71, 38, -27, 52, -55, -56, -17, -12, -40, 7, -50, -58, -7, -27, -38, -71, 66, 48, -71, 33, -39, 28, -34, 18, 46, -83, -23, -66, 
  25, -30, -19, -42, -62, -27, -38, 53, -36, 74, 4, -2, -54, 24, 40, -7, -65, 9, -66, 69, 23, -75, -37, -71, -58, 71, 20, -66, -76, -3, 21, -83, 62, -45, 32, 44, -67, -1, -58, 
  39, -99, 48, 15, 5, -68, 17, 22, -26, 58, -40, 61, 22, 31, -10, -100, 13, -44, -23, 52, -81, -7, 80, 15, -28, 63, 51, 19, -67, -24, 38, 37, -2, -58, -86, -31, -12, -37, 82, 
  45, -22, 15, 88, 0, 79, 65, 74, -7, 2, -19, 78, 67, 19, -63, 5, -11, -40, 60, -74, -14, 20, -86, 1, 45, -38, 113, -8, -63, -12, -36, 35, -85, -52, -27, -22, 12, -77, -57, 
  -16, -19, 45, -70, 11, 52, 31, 73, -69, 55, 83, 74, 56, 68, -76, -71, 36, -42, -37, -7, -13, 20, 15, -9, -22, 63, 11, 4, -76, 47, -62, -67, -40, 57, -14, 8, 73, 19, 27, 
  21, -10, 2, -30, 86, 19, -64, -65, 33, -25, -61, -14, 35, -103, 65, 59, 36, -46, -11, 79, -5, -42, -71, 40, 25, -64, 19, 39, -50, -39, -14, 37, 53, -24, -1, -2, 26, 41, -49, 
  28, 5, 79, 44, 20, 75, 42, 41, 70, 55, 54, 59, -57, 60, -32, 74, 21, 45, 53, -85, 53, -20, 47, 65, -69, 69, -23, -7, 22, -29, -32, -8, -83, -44, 12, -73, -2, 41, 11, 
  105, -105, 11, 54, -52, 36, -76, 29, -69, 35, 25, -12, -5, 85, 55, 3, 62, -59, -55, -56, -9, 66, 26, -63, -75, -34, 13, 4, -64, 93, -14, 71, 35, 74, 21, 47, 8, 52, -9, 
  36, -2, -51, 71, -33, 39, -39, 29, 7, -44, 76, -67, -87, 11, -84, -53, 56, 53, 84, -9, 66, -73, -5, 40, -3, -7, -14, -3, 86, 107, 35, -55, 40, -41, 32, 65, 39, -4, -55, 
  -46, 70, 25, 55, 50, 67, -24, 78, -50, 82, -22, -7, 74, 53, 1, 44, 50, -40, 26, -56, -19, 42, -71, -22, -28, 80, 49, 15, 26, 99, -51, 61, -84, 9, 28, 13, -74, -47, -33, 
  50, -66, -3, -20, 67, -65, 29, -49, 53, 62, 54, -75, -77, -99, -73, -56, -63, 56, -38, -70, -84, -45, 11, -20, -19, 62, 45, -6, -33, -53, -52, -25, -47, 1, 1, -3, -73, -23, 78, 
  11, -19, -72, 57, -53, 3, -5, -40, 56, -63, 2, 28, -25, -76, 46, -4, 45, 58, 52, -8, 74, 25, 40, -59, -52, 19, -101, -47, 48, -5, 84, -71, 77, -73, -59, 17, 21, -27, -12, 
  -7, 18, 59, -75, 53, -29, -11, -49, 29, -81, -45, -79, -67, -99, -10, -54, -30, -64, -4, -66, -58, -73, -56, 44, 27, -10, -97, -14, -7, -26, 38, 58, -63, -21, -31, -79, 75, -8, -42, 
  27, -1, 77, 76, 53, 53, -31, -47, -15, 40, 49, -61, -22, 57, -85, -47, 81, 61, 21, 1, 53, -14, 34, -71, 35, -32, 56, -14, 17, 25, 36, 74, 74, 33, -57, -25, -72, -4, 26, 
  -52, 19, -39, -7, -65, -53, 7, 32, 42, 11, 10, -63, 22, 6, 98, -66, 3, 27, 71, -25, -75, 44, -52, -20, -56, -17, 88, -28, -53, -16, -29, -50, 34, 10, -72, 4, 82, 86, 36, 
  -49, -15, -86, -48, 14, 34, -85, 52, -66, 48, -54, 52, -79, 80, 31, 56, 61, 87, 0, 40, 41, 18, 11, -13, -29, -54, 101, -85, -30, 37, -40, 81, 39, -16, 58, -32, 18, 64, -38, 
  -81, -67, -39, 39, -71, -45, -63, -11, 88, -17, -3, -55, -36, -38, -58, 43, 53, 44, -23, 64, 46, -12, 82, 56, 43, 16, 58, -17, -50, 24, -26, -23, 18, 36, 68, -22, 34, 32, 72, 
  71, -30, -9, 17, 28, 24, 18, 6, 70, 66, -36, 81, -28, 20, 3, 67, -34, 13, -71, 53, -7, 42, 71, 3, -54, -25, 13, 36, 60, -80, -37, -2, -49, -9, 5, -13, 80, 2, -69, 
  -13, -69, -22, 23, -28, 15, -79, 49, -61, -43, -22, 11, -6, -27, 31, 89, -11, -65, 55, -27, -19, 17, -18, -37, 68, 40, 39, -55, -5, 34, -42, -50, 62, -58, -7, -42, 76, -28, 7, 
  64, 93, -32, 88, 53, -47, -54, 78, -32, -17, -40, -12, -64, 5, 83, -35, 2, 22, 14, 44, -46, -27, 59, -83, -65, 41, 22, 76, -18, 18, -78, 42, -75, 16, -37, -33, 75, -71, 32, 
  34, -93, -78, 21, -26, -11, -18, -3, 59, 29, -23, -91, -52, -13, 42, 0, 49, -97, 71, 14, -86, 19, -70, -49, -53, -1, 127, -52, 24, 2, 82, 50, 24, 48, 64, 31, 52, 45, 34, 
  77, -87, 45, -99, 33, -48, 0, -52, -72, 87, -51, 40, 15, 71, -72, 2, -46, -56, -70, -63, 43, -47, 49, 29, 55, -3, 0, 53, 44, -28, -90, 59, -4, -57, 78, 19, 17, 14, -52, 
  -18, -64, -52, 27, -72, 39, 59, 18, 67, 67, -40, 55, 49, 81, 58, 23, -61, -27, 71, 31, 32, 58, 60, -13, 9, 20, 26, 23, -50, -1, 38, 81, -14, -35, -10, -42, -41, -12, 43, 
  104, -96, 47, 2, 14, -45, 27, -17, 48, 11, 53, 25, 67, 61, 11, 47, 81, -67, -62, -20, -8, 62, 59, -75, -40, 52, -37, -21, 56, 73, -55, 5, -53, -84, -70, 47, 71, 13, -68, 
  -62, 51, 72, 46, -48, -32, 42, -18, 47, 47, 39, -22, 39, 57, 3, -54, -72, -84, -59, 82, -15, -56, 15, 40, -17, 7, -37, 63, 2, 30, 54, -66, 34, 75, -1, 55, 17, -60, 36, 
  -45, 99, 71, 28, 24, -10, -36, -27, -49, -35, 46, 5, 64, -12, -90, -39, 21, 79, -49, 52, -16, 71, -85, -19, 70, 44, -73, 79, -44, 50, 80, -45, 57, 41, -35, -85, -75, -86, -25, 
  -18, 8, -16, -1, -32, -89, 47, -70, -21, -81, 51, -25, 72, -48, -68, -61, -100, -1, 37, -43, -68, -62, 62, -45, 74, 12, 42, 48, 58, 42, -22, 2, 38, 17, -55, 17, 21, -66, -13, 
  29, -83, 92, 42, -81, 26, 11, 36, -19, 7, -23, -57, 51, 9, -54, 83, -44, 61, -65, 45, 13, 20, -20, 58, 42, 0, 78, 48, 65, 49, -25, 14, -56, 66, -18, 67, -64, 62, 10, 
  -57, 92, 50, -71, -14, -20, -34, -20, -30, 38, -66, 60, 0, -54, 21, -8, 11, 0, -40, -28, -69, -12, 65, -59, 54, -65, 18, 94, -21, 70, 69, 21, 7, -6, 19, -23, -40, 6, -57, 
  35, 32, 36, -9, -14, -73, -56, -56, -56, -54, 13, -57, 11, 23, 26, -66, 75, 18, -79, 29, -24, 15, 49, -47, 35, -20, -19, -10, -16, 37, 54, -77, 36, 32, 26, 29, 5, 53, -75, 
  45, 54, -46, -20, 57, -60, -36, 37, 78, -32, -9, -52, -7, 79, 66, -45, -61, 13, -9, -73, 83, 57, 39, 59, 72, 43, 56, 70, 23, -85, -54, 27, -59, 41, 35, -60, -69, -57, 20, 
  -34, -15, -7, 85, -98, 4, 51, 24, 17, -5, 26, 64, -61, 42, 61, -16, -18, -13, 44, 8, -75, 37, 7, 65, -58, -63, 14, -56, 72, 11, -16, -33, -69, -22, -50, -3, -26, 19, -80, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 50,39 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0031554633751511574, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,50 } };
const TfArray<1, float> quant7_scale = { 1, { 0.047011159360408783, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,20 } };
const TfArray<1, float> quant8_scale = { 1, { 0.048858754336833954, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.038559209555387497, } };
const TfArray<1, int> quant9_zero = { 1, { -4 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 39, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 1000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1950, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 50, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension8, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_947452_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_947452_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_947452_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_947452_5_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_947452_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
